package com.tencent.qqnt.kernelpublic.nativeinterface;

/* compiled from: P */
/* loaded from: classes2.dex */
public enum GroupNotifyMsgType {
    UNSPECIFIED,
    INVITEDBYMEMBER,
    REFUSEINVITED,
    REFUSEDBYADMINISTRATOR,
    AGREEDTOJOINDIRECT,
    INVITEDNEEDADMINISTRATORPASS,
    AGREEDTOJOINBYADMINISTRATOR,
    REQUESTJOINNEEDADMINISTRATORPASS,
    SETADMIN,
    KICKMEMBERNOTIFYADMIN,
    KICKMEMBERNOTIFYKICKED,
    MEMBERLEAVENOTIFYADMIN,
    CANCELADMINNOTIFYCANCELED,
    CANCELADMINNOTIFYADMIN,
    TRANSFERGROUPNOTIFYOLDOWNER,
    TRANSFERGROUPNOTIFYADMIN
}
