package com.tencent.qqnt.kernelpublic.nativeinterface;

/* compiled from: P */
/* loaded from: classes.dex */
public enum SearchLocalBusinessType {
    KSEARCHLOCALBUSINESSTYPEUNKNOWN,
    KSEARCHLOCALBUSINESSTYPEALL,
    KSEARCHLOCALBUSINESSTYPECREATEGROUP,
    KSEARCHLOCALBUSINESSTYPEFORWARD,
    KSEARCHLOCALBUSINESSTYPEDESKTOPALL,
    KSEARCHLOCALBUSINESSTYPEDESKTOPBUDDY,
    KSEARCHLOCALBUSINESSTYPEDESKTOPGROUP,
    KSEARCHLOCALBUSINESSTYPEMQQALL
}
